##sparql --results=CSV --data=../resources/be/vlaanderen/omgeving/data/id/conceptscheme/chemische_stof/chemische_stof.ttl  --query rdf_to_csv.rq >

prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
prefix dbo:   <http://dbpedia.org/ontology/> 
prefix cs:    <https://data.vlaanderen.be/ns/chemische_stof#> 
prefix dbp:   <http://dbpedia.org/property/>
prefix dct:   <http://purl.org/dc/terms/>
prefix xkos:   <http://rdf-vocabulary.ddialliance.org/xkos#>
prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>



select distinct
?uri
?inchikey
?prefLabel
?altLabel
?notation
?definition
?note
?comment
?casNumber
?inchi
?iupacName
?smiles
?formula
?pubchem
?seeAlso
?levels
?exactMatch
?broader
?broaderTransitive
?narrower
?dct_type
?type
?collection
?member
?first
?rest
?depth
?hasTopConcept
?belongsTo
?topConceptOf
?inScheme
where 
{?uri a ?type .
optional {?uri skos:altLabel ?altLabel }
optional {?uri skos:definition ?definition }
optional {?uri skos:exactMatch ?exactMatch }
optional {?uri dct:type ?dct_type }
optional {?uri skos:broader ?broader }
optional {?uri skos:notation ?notation }
optional {?uri skos:prefLabel ?prefLabel }
optional {?uri dbo:casNumber ?casNumber }
optional {?uri dbo:inchi ?inchi}
optional {?uri dbo:iupacName ?iupacName }
optional {?uri dbo:pubchem ?pubchem }
optional {?uri dbo:smiles ?smiles }
optional {?uri dbo:formula ?formula }
optional {?uri skos:note ?note }
optional {?uri rdfs:seeAlso ?seeAlso .}
optional {?uri dbp:inchikey ?inchikey }
optional {?uri skos:broaderTransitive ?broaderTransitive .}
optional {?collection skos:member ?uri .}
optional {?uri skos:member ?member .}
optional {?uri skos:narrower ?narrower .}
optional {?uri rdf:rest ?rest .}
optional {?uri rdf:first ?first .}
optional {?uri skos:comment ?comment .}
optional {?uri xkos:levels ?levels .}
optional {?uri xkos:belongsTo ?belongsTo .}
optional {?uri xkos:depth ?depth .}
optional {?uri skos:hasTopConcept ?hasTopConcept .}
optional {?uri skos:topConceptOf ?topConceptOf .}
optional {?uri skos:inScheme ?inScheme .}


}


